spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-cafe;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  messages:
    basename: errors

server:
  servlet:
    session:
      tracking-modes: cookie
