spring:
  mustache:
    cache: false
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-qna-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com: debug

server:
  port: 8080
