spring:
  mustache:
    cache: false
    expose-session-attributes: true
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bcb35822584fbe:501c0042@us-cdbr-east-05.cleardb.net/heroku_4e96821042e4948?reconnect=true&serverTimezone=Asia/Seoul
    username: bcb35822584fbe
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    session:
      tracking-modes: cookie
