spring:
  mustache:
    cache: false
    expose-session-attributes: true
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/springcafe
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      tracking-modes: cookie
