spring:
  profiles:
    active: ${profile}
  mustache:
    cache: false
    expose-session-attributes: true
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      schema-locations: classpath:sql/ddl.sql
      mode: always
server:
  servlet:
    session:
      tracking-modes: cookie
