spring:
  mustache:
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/springcafe
    username: sa
    password:
