drop table if exists article;
drop table if exists user;

create table article
(
    index        int generated by default as identity,
    writer       varchar(50),
    title        varchar(50),
    contents     text,
    datetime     varchar(50),
    primary key (index)
);

create table user
(
    id        int generated by default as identity,
    userid      varchar(50),
    name        varchar(50),
    password    varchar(50),
    email       varchar(100),
    primary key (id)
);

