drop table if exists post CASCADE;

CREATE TABLE post (
     id bigint generated by default as identity,
     writer VARCHAR(255),
     title VARCHAR(255),
     content VARCHAR(255),
     localdatetime TIMESTAMP,
     primary key (id)
);

drop table if exists `user` CASCADE;

create table `user`
(
    id   bigint generated by default as identity,
    user_id VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    `name` VARCHAR(50),
    email VARCHAR(100),
    primary key (id)
);
