DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS TEST
(
    ID INT PRIMARY KEY,
    NAME VARCHAR (255)
);

DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE IF NOT EXISTS ARTICLE
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR (255),
    TITLE VARCHAR (255),
    CONTENT VARCHAR (255),
    VIEW_COUNT INT,
    CREATED_AT TIMESTAMP
);
