INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');

INSERT INTO ARTICLE (USER_ID, TITLE, CONTENT, VIEW_COUNT, CREATED_AT)
VALUES('TEST1', 'TEST TITLE1', 'TEST CONTENT1', 0, CURRENT_TIMESTAMP);
INSERT INTO ARTICLE (USER_ID, TITLE, CONTENT, VIEW_COUNT, CREATED_AT)
VALUES('TEST2', 'TEST TITLE2', 'TEST CONTENT2', 0, CURRENT_TIMESTAMP);
INSERT INTO ARTICLE (USER_ID, TITLE, CONTENT, VIEW_COUNT, CREATED_AT)
VALUES('TEST3', 'TEST TITLE3', 'TEST CONTENT3', 0, CURRENT_TIMESTAMP);

INSERT INTO MEMBER (USER_ID, EMAIL, PASSWORD, CREATED_AT)
VALUES('TEST1', 'test1@user.com', 'password1', CURRENT_TIMESTAMP);
INSERT INTO MEMBER (USER_ID, EMAIL, PASSWORD, CREATED_AT)
VALUES('TEST2', 'test2@user.com', 'password2', CURRENT_TIMESTAMP);
INSERT INTO MEMBER (USER_ID, EMAIL, PASSWORD, CREATED_AT)
VALUES('TEST3', 'test3@user.com', 'password3', CURRENT_TIMESTAMP);
