drop table if exists article;

create table article
(
    index        int generated by default as identity,
    writer       varchar(50),
    title        varchar(50),
    contents     text,
    datetime     varchar(50),
    primary key (index)
);

