drop table if exists `user` cascade;
create table `user`
(
    id       int generated by default as identity,
    nickname varchar(255),
    email    varchar(255),
    date     date,
    password varchar(255),
    primary key (id)
);

drop table if exists article cascade;
create table article
(
    id      int generated by default as identity,
    title   varchar(255),
    date    date,
    content text,
    primary key (id)
);
