DROP TABLE IF EXISTS questionTbl CASCADE;
CREATE TABLE questionTbl (
                      id bigint generated by default as identity,
                      writer VARCHAR(255),
                      title VARCHAR(255),
                      contents VARCHAR(3000),
                      primary key (id)
);


DROP TABLE IF EXISTS userTbl CASCADE;
create table userTbl
(
    id   bigint generated by default as identity,
    userId VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    name VARCHAR(50),
    email VARCHAR(100),
    primary key (id)
);
