-- DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50) NOT NULL,
    NAME VARCHAR(50),
    EMAIL VARCHAR(50)
);

-- DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WRITER VARCHAR(50) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    CONTENTS TEXT,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

