DROP TABLE if exists article CASCADE;
CREATE TABLE article (
    article_id bigint generated by default  as identity,
    title varchar(255),
    content varchar,
    writer varchar(255),
    reg_date_time timestamp,
    primary key (article_id)
);