create table user
(
    id bigint generated by default as identity,
    userId varchar(255),
    password varchar(255),
    name varchar(255),
    email varchar(255),
    primary key (id)
)

create table article
(
    id bigint generated by default as identity,
    writer varchar(255),
    title varchar(255),
    content varchar(255),
    localdatetime varchar(255),
    primary key (id)
)
